version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y hugo
  build:
    commands:
      - hugo --config hugo.yaml
  post_build:
    commands:
      - aws s3 cp ./public/ $(echo $S3_BUCKET) --recursive
